file=open("codingal3.txt","r")
print(file.read())
file.close()
file=open("codingal3.txt","r")
print("\n read first 10 characters \n")
print(file.read(10))
file.close()
file=open("codingal3.txt","r")
print("\nread first line \n")
print(file.readline(30))
file.close()
file=open("codingal3.txt","r")
print("\nread first four lines \n")
print(file.readline())
print(file.readline())
print(file.readline())
print(file.readline())
file.close()
file=open("codingal3.txt","r")
for x in file:
    print(x)
file.close()    