file=open("codingal1.txt","r")
print(file.read())
file.close()
file_write=open("codingal1.txt","w")
file_write.write("my name is Poorva")
file_write.write("\ni am 16 years old")
file_write.close()
file_append=open("codingal1.txt","a")
file_append.write("\nmy favourite subject is maths")
file_append.close()