file=open("codingal.txt","r")
print("file in read mode")
print(file.read())
file.close()
file_write=open("codingal.txt","w")
file_write.write("file in write mode")
file_write.write("this is a new text")
file_write.close()
file_append=open("codingal.txt","a")
file_append.write("\nfile in append mode")
file_append.write("new text in append mode")
file_append.close()