file_read=open("codingal2.txt","r")
print("file in read mode-")
print(file_read.read())
file_read.close()
file_write=open("codingal2.txt","w")
file_write.write("file in write mode...")
file_write.write("\nthis is a write text")
file_write.close()
file_append=open("codingal2.txt","a")
file_append.write("\nfile in append mode...")
file_append.write("\nthis is an append text")
file_append.close()